apiVersion: v2
name: lightwell-tssc-workshop
description: App of Apps — Lightwell TSSC workshop components via ArgoCD Applications
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: NA-FSI-Services
    url: https://github.com/NA-FSI-Services/lightwell-tssc-workshop
