{{- if and .Values.parasolApp.enabled .Values.userInfo.enabled }}
{{- $appUrl := include "parasol-app.appUrl" . }}
{{- $nexusUrl := include "parasol-app.nexusUrl" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-userinfo-parasol-app
  namespace: {{ .Values.parasolApp.namespace }}
  labels:
    {{- include "parasol-app.labels" . | nindent 4 }}
    demo.redhat.com/userinfo: ""
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.parasolApp.syncWaves.userinfo | quote }}
data:
  demo_title: {{ .Values.userInfo.title | quote }}
  access_instructions: {{ .Values.userInfo.instructions | quote }}
  deployment_type: "helm"
  optional_component: "true"
  primary_app: "spring-boot-lw-poc"
  app_url: {{ $appUrl | quote }}
  nexus_url: {{ $nexusUrl | quote }}
  channel_validated: {{ .Values.lightwell.validatedRepo | quote }}
  channel_remediated: {{ .Values.lightwell.remediatedRepo | quote }}
  upstream_url: {{ .Values.upstream.url | quote }}
  cluster_domain: {{ .Values.deployer.domain | quote }}
  cluster_api_url: {{ .Values.deployer.apiUrl | quote }}
{{- end }}
