{{- if and .Values.rhdh.enabled .Values.userInfo.enabled }}
{{- $baseUrl := include "rhdh.baseUrl" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-userinfo-rhdh
  namespace: {{ .Values.rhdh.namespace }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
    demo.redhat.com/userinfo: ""
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rhdh.syncWaves.userinfo | quote }}
data:
  demo_title: {{ .Values.userInfo.title | quote }}
  access_instructions: {{ .Values.userInfo.instructions | quote }}
  deployment_type: "helm"
  operator_name: {{ .Values.operator.name | quote }}
  rhdh_namespace: {{ .Values.rhdh.namespace | quote }}
  rhdh_name: {{ .Values.rhdh.name | quote }}
  rhdh_url: {{ $baseUrl | quote }}
  software_template: "lightwell-java-service"
  software_template_python: "lightwell-python-service"
  cluster_domain: {{ .Values.deployer.domain | quote }}
  cluster_api_url: {{ .Values.deployer.apiUrl | quote }}
{{- end }}
