{{- if .Values.rhacs.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhacs.namespace }}
  labels:
    {{- include "rhacs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rhacs.syncWaves.namespace | quote }}
{{- if and .Values.operator.enabled (ne .Values.operator.namespace .Values.rhacs.namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  labels:
    {{- include "rhacs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rhacs.syncWaves.namespace | quote }}
{{- end }}
{{- end }}
