{{- if .Values.rhdh.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.rhdh.namespace }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rhdh.syncWaves.namespace | quote }}
{{- if and .Values.operator.enabled (ne .Values.operator.namespace .Values.rhdh.namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operator.namespace }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.rhdh.syncWaves.namespace | quote }}
{{- end }}
{{- end }}
