{{- if and .Values.pipelines.enabled .Values.userInfo.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-userinfo-pipelines
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "pipelines.labels" . | nindent 4 }}
    demo.redhat.com/userinfo: ""
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.pipelines.syncWaves.userinfo | quote }}
data:
  demo_title: {{ .Values.userInfo.title | quote }}
  access_instructions: {{ .Values.userInfo.instructions | quote }}
  operator_subscription: {{ .Values.operator.name | quote }}
  operator_namespace: {{ .Values.operator.namespace | quote }}
  pipelines_namespace: openshift-pipelines
  cluster_domain: {{ .Values.deployer.domain | quote }}
  cluster_api_url: {{ .Values.deployer.apiUrl | quote }}
  deployment_type: helm
{{- end }}
