{{- if .Values.renovate.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.renovate.namespace }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.renovate.syncWaves.namespace | quote }}
{{- end }}
