#!/usr/bin/env bash
# Ensure a single workshop learner (user1) password for ephemeral claim QA.
#
# - Username defaults to user1 (only student seeded into Gitea for instruction tests)
# - Password: reuse WORKSHOP_USER_PASSWORD from claim.env / workshop-user.env, or generate
# - Writes credentials to gitignored files and prints them for the provision requestor / agents
#
# Usage:
#   source scripts/dev-cluster-workshop-user.sh   # sets WORKSHOP_USER / WORKSHOP_USER_PASSWORD
#   ./scripts/dev-cluster-workshop-user.sh        # generate/persist + print banner
#
# See docs/DEV-CLUSTER-WORKSHOP-USER.md
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLAIM_ENV="${CLAIM_ENV:-${ROOT}/dev-cluster/claim.env}"
WORKSHOP_USER_ENV="${WORKSHOP_USER_ENV:-${ROOT}/dev-cluster/workshop-user.env}"

WORKSHOP_USER="${WORKSHOP_USER:-user1}"

_load_existing_password() {
  if [[ -n "${WORKSHOP_USER_PASSWORD:-}" ]]; then
    return 0
  fi
  if [[ -f "${WORKSHOP_USER_ENV}" ]]; then
    # shellcheck disable=SC1090
    set -a && source "${WORKSHOP_USER_ENV}" && set +a
  fi
  if [[ -z "${WORKSHOP_USER_PASSWORD:-}" && -f "${CLAIM_ENV}" ]]; then
    # shellcheck disable=SC1090
    set -a && source "${CLAIM_ENV}" && set +a
  fi
}

_generate_password() {
  # Alphanumeric only — safe in git HTTPS URLs and Helm --set values
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '/+=\n' | head -c 24
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
  fi
}

_upsert_env_file() {
  local file="$1" key="$2" value="$3"
  mkdir -p "$(dirname "${file}")"
  touch "${file}"
  if grep -qE "^${key}=" "${file}" 2>/dev/null; then
    # Portable in-place replace without committing secrets to git history via sed backup
    local tmp
    tmp="$(mktemp)"
    awk -v k="${key}" -v v="${value}" '
      BEGIN { done=0 }
      $0 ~ "^" k "=" { print k "=" v; done=1; next }
      { print }
      END { if (!done) print k "=" v }
    ' "${file}" >"${tmp}"
    mv "${tmp}" "${file}"
  else
    printf '%s=%s\n' "${key}" "${value}" >>"${file}"
  fi
}

_persist() {
  local generated="${1:-false}"
  umask 077
  {
    echo "# Generated by scripts/dev-cluster-workshop-user.sh — DO NOT COMMIT"
    echo "# See docs/DEV-CLUSTER-WORKSHOP-USER.md"
    # Quote values so bash `source` is safe when FULL_NAME (etc.) contains spaces.
    printf "WORKSHOP_USER=%q\n" "${WORKSHOP_USER}"
    printf "WORKSHOP_USER_PASSWORD=%q\n" "${WORKSHOP_USER_PASSWORD}"
    printf "WORKSHOP_USER_EMAIL=%q\n" "${WORKSHOP_USER_EMAIL:-${WORKSHOP_USER}@workshop.local}"
    printf "WORKSHOP_USER_FULL_NAME=%q\n" "${WORKSHOP_USER_FULL_NAME:-Workshop User 1}"
  } >"${WORKSHOP_USER_ENV}"

  if [[ -f "${CLAIM_ENV}" ]]; then
    _upsert_env_file "${CLAIM_ENV}" "WORKSHOP_USER" "${WORKSHOP_USER}"
    _upsert_env_file "${CLAIM_ENV}" "WORKSHOP_USER_PASSWORD" "${WORKSHOP_USER_PASSWORD}"
  fi

  if [[ "${generated}" == "true" ]]; then
    echo "dev-cluster-workshop-user: generated new WORKSHOP_USER_PASSWORD (saved to workshop-user.env + claim.env)" >&2
  else
    echo "dev-cluster-workshop-user: reusing existing WORKSHOP_USER_PASSWORD" >&2
  fi
}

print_workshop_user_banner() {
  local domain="${DEPLOYER_DOMAIN:-<DEPLOYER_DOMAIN>}"
  cat <<EOF

================================================================================
 WORKSHOP LEARNER CREDENTIALS (dev-cluster QA only — do not commit)
================================================================================
  Username:     ${WORKSHOP_USER}
  Password:     ${WORKSHOP_USER_PASSWORD}
  Email:        ${WORKSHOP_USER_EMAIL:-${WORKSHOP_USER}@workshop.local}

  Gitea UI:     https://gitea.${domain}/
  App repo:     https://gitea.${domain}/${WORKSHOP_USER}/spring-boot-lw-poc.git
  GitOps repo:  https://gitea.${domain}/${WORKSHOP_USER}/gitops-spring-boot-lw-poc.git
  Promote NS:   lw-poc-${WORKSHOP_USER}
  Argo app:     lw-poc-${WORKSHOP_USER}

  Persisted:    ${WORKSHOP_USER_ENV}
                ${CLAIM_ENV} (WORKSHOP_USER / WORKSHOP_USER_PASSWORD)

  AGENTS: use this password for Module 5 / Gitea / promote workshop tests.
  Docs:   docs/DEV-CLUSTER-WORKSHOP-USER.md
================================================================================

EOF
}

ensure_workshop_user() {
  _load_existing_password
  local generated=false
  if [[ -z "${WORKSHOP_USER_PASSWORD:-}" ]]; then
    WORKSHOP_USER_PASSWORD="$(_generate_password)"
    generated=true
  fi
  WORKSHOP_USER_EMAIL="${WORKSHOP_USER_EMAIL:-${WORKSHOP_USER}@workshop.local}"
  WORKSHOP_USER_FULL_NAME="${WORKSHOP_USER_FULL_NAME:-Workshop User 1}"
  export WORKSHOP_USER WORKSHOP_USER_PASSWORD WORKSHOP_USER_EMAIL WORKSHOP_USER_FULL_NAME
  _persist "${generated}"
}

# When executed (not sourced), ensure + print banner
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  if [[ -f "${CLAIM_ENV}" ]]; then
    # shellcheck disable=SC1090
    set -a && source "${CLAIM_ENV}" && set +a
  fi
  ensure_workshop_user
  print_workshop_user_banner
fi
