spring.application.name=${{ values.name }}
server.port=8080
management.endpoints.web.exposure.include=health,info
lightwell.stream=${lightwell.stream:validated}
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
