{{- if .Values.validateJobs.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scriptsConfigMap }}
  namespace: {{ .Values.validateJobs.namespace }}
  labels:
    {{- include "validate-jobs.labels" . | nindent 4 }}
    app.kubernetes.io/component: scripts
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.validateJobs.syncWaves.scripts | quote }}
data:
{{- range $path, $_ := .Files.Glob "files/*.sh" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
